"""itermux-bridge CLI: install / uninstall / status / logs / doctor (design §9)."""

import argparse
import os
import shutil
import socket
import subprocess
import sys
from pathlib import Path

from .config import CONFIG_PATH, Config

def _support_dir() -> Path:
    """Find iTerm2's Application Support dir.

    It is NOT always ~/Library/Application Support/iTerm2 — iTerm2 honours a
    custom location (observed in the wild: ~/.config/iterm2/AppSupport), so
    prefer whichever already exists rather than hardcoding one.
    """
    candidates = [
        Path.home() / ".config/iterm2/AppSupport",
        Path.home() / "Library/Application Support/iTerm2",
    ]
    for c in candidates:
        if (c / "Scripts").is_dir():
            return c
    for c in candidates:
        if c.is_dir():
            return c
    return candidates[-1]


AUTOLAUNCH = _support_dir() / "Scripts/AutoLaunch"
SCRIPT_DIR = AUTOLAUNCH / "itermux_bridge"

# iTerm2 launches AutoLaunch scripts with its own bundled Python (iterm2env),
# which it downloads on demand and which won't have our package importable. To
# stay self-contained we re-exec under the interpreter that actually has our
# deps (the repo venv), then hand off to main().
LAUNCHER = """\
#!/usr/bin/env python3
# Auto-generated by `itermux-bridge install`. Runs as an iTerm2 AutoLaunch script.
import os
import sys

REPO = {repo!r}
PYTHON = {python!r}

# Re-exec under the interpreter that actually has `iterm2` importable.
#
# Do NOT compare interpreter paths here: a venv's bin/python3 is a symlink to
# the base interpreter, so realpath() reports them as the same file even though
# only the venv has site-packages on sys.path. Ask the real question instead —
# "can I import iterm2?" — and re-exec if not. The guard env var stops an
# exec loop if the venv is broken too.
try:
    import iterm2  # noqa: F401
except ImportError:
    if os.environ.get("ITMUX_REEXEC") != "1" and os.path.exists(PYTHON):
        os.environ["ITMUX_REEXEC"] = "1"
        os.execv(PYTHON, [PYTHON, os.path.abspath(__file__)])
    raise

sys.path.insert(0, REPO)

from itermux_bridge.main import main

main()
"""


def _can_import_iterm2(python: Path) -> bool:
    """Can `python` import iterm2? Asked by running it, not by guessing."""
    try:
        r = subprocess.run([str(python), "-c", "import iterm2"],
                           capture_output=True, timeout=30)
        return r.returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def cmd_install(args) -> int:
    # The directory our package sits in — a git checkout, or Homebrew's
    # libexec/.../site-packages. Either way it is what has to go on sys.path.
    repo = Path(__file__).resolve().parent.parent

    # The interpreter that can `import iterm2`. In a git checkout that is the
    # repo venv; under Homebrew it is the libexec venv already running us, and
    # sys.executable is correct. Verify rather than assume, so a broken install
    # is caught here instead of silently producing a launcher that can't start.
    venv_python = repo / ".venv" / "bin" / "python3"
    python = venv_python if venv_python.exists() else Path(sys.executable)
    if not _can_import_iterm2(python):
        print(f"❌ {python} cannot import `iterm2`.")
        print("   In a git checkout: python3 -m venv .venv && "
              ".venv/bin/pip install iterm2")
        return 1

    SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    launcher = SCRIPT_DIR / "itermux_bridge.py"
    launcher.write_text(LAUNCHER.format(repo=str(repo), python=str(python)))
    launcher.chmod(0o755)

    cfg = Config.write_default()
    print(f"✅ installed AutoLaunch script: {launcher}")
    print(f"📝 config: {cfg}")
    print()
    print("Next:")
    print("  1. iTerm2 → Settings → General → Magic → enable “Python API”")
    print("  2. Restart iTerm2 (or Scripts → itermux_bridge to start it now)")
    print("  3. Approve the API-permission prompt when it appears")
    print(f"  4. tmux -S {Config.load().socket_path} attach")
    return 0


def cmd_uninstall(args) -> int:
    if SCRIPT_DIR.exists():
        shutil.rmtree(SCRIPT_DIR)
        print(f"🗑️  removed {SCRIPT_DIR}")
    else:
        print("nothing to remove")
    return 0


def _socket_live(path: Path) -> bool:
    if not path.exists():
        return False
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        s.connect(str(path))
        return True
    except OSError:
        return False
    finally:
        s.close()


def cmd_status(args) -> int:
    cfg = Config.load()
    live = _socket_live(cfg.socket_path)
    print(f"socket:  {cfg.socket_path}")
    print(f"status:  {'🟢 running' if live else '🔴 not running'}")
    print(f"install: {'yes' if SCRIPT_DIR.exists() else 'no'}  ({SCRIPT_DIR})")
    if live:
        print(f"\nattach:  tmux -S {cfg.socket_path} attach")
    return 0 if live else 1


def cmd_logs(args) -> int:
    cfg = Config.load()
    if not cfg.log_path.exists():
        print(f"no log yet at {cfg.log_path}")
        return 1
    cmd = ["tail"] + (["-f"] if args.follow else ["-n", "50"]) + [str(cfg.log_path)]
    return subprocess.call(cmd)


def _find_tmux():
    """tmux on PATH, or in Homebrew's bin dirs.

    A non-interactive SSH shell doesn't have Homebrew on PATH, so which()
    alone reported an installed tmux as missing.
    """
    found = shutil.which("tmux")
    if found:
        return found
    for cand in ("/opt/homebrew/bin/tmux", "/usr/local/bin/tmux"):
        if os.access(cand, os.X_OK):
            return cand
    return None


def _runtime_installed() -> bool:
    return any(_support_dir().glob("iterm2env*"))


def cmd_doctor(args) -> int:
    cfg = Config.load()
    ok = True

    def check(label, good, hint=""):
        nonlocal ok
        print(f"  {'✅' if good else '❌'} {label}")
        if not good and hint:
            print(f"     → {hint}")
        ok = ok and good

    print("🩺 itermux-bridge doctor\n")

    check("macOS", sys.platform == "darwin", "iTerm2 is macOS-only")

    try:
        import iterm2  # noqa: F401
        have = True
    except ImportError:
        have = False
    check("iterm2 python package", have, "pip install iterm2")

    api = subprocess.run(
        ["defaults", "read", "com.googlecode.iterm2", "EnableAPIServer"],
        capture_output=True, text=True)
    check("iTerm2 Python API enabled", api.stdout.strip() == "1",
          "iTerm2 → Settings → General → Magic → Enable Python API")

    tmux = _find_tmux()
    check("tmux installed", bool(tmux), "brew install tmux")
    if tmux:
        ver = subprocess.run([tmux, "-V"], capture_output=True, text=True)
        v = ver.stdout.strip()
        # We implement PROTOCOL_VERSION 8, which covers tmux 3.x.
        print(f"     {v} (bridge implements protocol version 8)")

    check("installed as AutoLaunch script", SCRIPT_DIR.exists(),
          "run: itermux-bridge install")
    # iTerm2 runs AutoLaunch scripts with its own Python runtime; without it
    # the script is never started and nothing says why -- the bridge simply
    # isn't there after iTerm2 launches (seen on a fresh machine).
    check("iTerm2 Python runtime installed (needed to auto-start)",
          _runtime_installed(),
          "iTerm2 → Scripts → Manage → Install Python Runtime")
    check("bridge running", _socket_live(cfg.socket_path),
          "start iTerm2, or Scripts → itermux_bridge")

    print("\n" + ("all good ✨" if ok else "issues above ⚠️"))
    return 0 if ok else 1


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        prog="itermux-bridge",
        description="Expose iTerm2 sessions over the tmux protocol.")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("install", help="install as an iTerm2 AutoLaunch script")
    sub.add_parser("uninstall", help="remove the AutoLaunch script")
    sub.add_parser("status", help="is the gateway running?")
    sub.add_parser("doctor", help="diagnose setup problems")
    lg = sub.add_parser("logs", help="show the log")
    lg.add_argument("-f", "--follow", action="store_true")

    args = p.parse_args(argv)
    return {
        "install": cmd_install, "uninstall": cmd_uninstall,
        "status": cmd_status, "logs": cmd_logs, "doctor": cmd_doctor,
    }[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
